#!/bin/bash

# Quick Commands Reference for Punyaka MVP

echo "🕉️ Punyaka MVP - Quick Commands"
echo "================================"
echo ""

# Function to display section
section() {
    echo ""
    echo "### $1 ###"
    echo ""
}

section "START APPLICATION"
echo "docker-compose up --build"
echo ""
echo "Or in detached mode:"
echo "docker-compose up --build -d"

section "VIEW LOGS"
echo "All services:"
echo "  docker-compose logs -f"
echo ""
echo "Backend only:"
echo "  docker-compose logs -f backend"
echo ""
echo "Frontend only:"
echo "  docker-compose logs -f frontend"
echo ""
echo "Database only:"
echo "  docker-compose logs -f db"

section "STOP APPLICATION"
echo "docker-compose down"
echo ""
echo "Stop and remove volumes (reset database):"
echo "docker-compose down -v"

section "RESTART SERVICES"
echo "docker-compose restart"
echo ""
echo "Restart specific service:"
echo "docker-compose restart backend"

section "EXECUTE COMMANDS IN CONTAINERS"
echo "Backend shell:"
echo "  docker-compose exec backend sh"
echo ""
echo "Frontend shell:"
echo "  docker-compose exec frontend sh"
echo ""
echo "Database shell:"
echo "  docker-compose exec db psql -U punyaka_user -d punyaka_db"

section "DJANGO COMMANDS (from backend container)"
echo "Create migrations:"
echo "  python manage.py makemigrations"
echo ""
echo "Run migrations:"
echo "  python manage.py migrate"
echo ""
echo "Create superuser:"
echo "  python manage.py createsuperuser"
echo ""
echo "Load fixtures:"
echo "  python manage.py loaddata demo_data.json"
echo ""
echo "Django shell:"
echo "  python manage.py shell"

section "REBUILD FROM SCRATCH"
echo "docker-compose down -v"
echo "docker-compose build --no-cache"
echo "docker-compose up"

section "CHECK SERVICE STATUS"
echo "docker-compose ps"

section "VIEW RESOURCE USAGE"
echo "docker-compose stats"

section "ACCESS URLS"
echo "Frontend:  http://localhost:3000"
echo "Backend:   http://localhost:8000/api"
echo "Admin:     http://localhost:8000/admin"
echo "API Docs:  http://localhost:8000/api/swagger/"
echo "ReDoc:     http://localhost:8000/api/redoc/"

section "DEMO CREDENTIALS"
echo "Admin:     admin@punyaka.com / admin123"
echo "Priest 1:  priest1@punyaka.com / priest123"
echo "Priest 2:  priest2@punyaka.com / priest123"
echo "Priest 3:  priest3@punyaka.com / priest123"
echo "Customer:  customer1@punyaka.com / customer123"

section "TROUBLESHOOTING"
echo "Port conflicts:"
echo "  lsof -i :3000"
echo "  lsof -i :8000"
echo "  lsof -i :5432"
echo ""
echo "Remove all containers and images:"
echo "  docker-compose down --rmi all"
echo ""
echo "Check Docker system:"
echo "  docker system df"
echo "  docker system prune"

echo ""
echo "================================"
echo "For detailed docs, see:"
echo "  - README.md (quick overview)"
echo "  - SETUP.md (detailed setup)"
echo "  - DEMO_CHECKLIST.md (demo guide)"
echo "  - STATUS.md (project status)"
echo "================================"
